apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: worldtimeapi
spec:
  hosts:
  - worldtimeapi.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /time
    route:
    - destination:
        host: back-service
        port:
          number: 8000
  - match:
    - uri:
        prefix: /other-endpoint
    route:
    - destination:
        host: other-service
        port:
          number: 8080